import { Tokenizer } from "types/ml/Tokenizer";

test("tokenize works", () => {
    const actual1 = Tokenizer.charTranslateString("Seán Seosamh Ó h'Éalaí");
    const actual2 = Tokenizer.charTranslateString("Tomáš Mikolov");
    const actual3 = Tokenizer.charTranslateString("Κυριάκος Μητσοτάκης");
    const actual4 = Tokenizer.charTranslateString("Владимир Владимирович Путин");
    expect(actual1).toBe("sean seosamh o h'ealai");
    expect(actual2).toBe("tomas mikolov");
    expect(actual3).toBe("kyriakos mitsotakis");
    expect(actual4).toBe("vladimir vladimirovich putin");
});


test("latinize greek", () => {
    const s = `Κατά την Εποχή των ανακαλύψεων το 15ο και 16ο αιώνα, η Πορτογαλία και η Ισπανία πρωτοστάτησαν στην ευρωπαϊκή εξερεύνηση του πλανήτη και εγκαθίδρυσαν τεράστιες πολυπληθείς αυτοκρατορίες. Εποφθαλμιώντας τον πλούτο που προσέφεραν αυτές οι αυτοκρατορίες, η Αγγλία, η Γαλλία και η Ολλανδία άρχισαν και αυτές να ιδρύουν αποικίες και εμπορικά δίκτυα στην Αμερική και την Ασία.[4] Μία σειρά πολέμων το 17ο και 18ο αιώνα ενάντια στην Ολλανδία και τη Γαλλία κατέστησε την Αγγλία (Βρετανία μετά την πράξη ένωσης με τη Σκωτία το 1707) κυρίαρχη αποικιακή δύναμη στη Βόρεια Αμερική και την Ινδία. Η απώλεια όμως των δεκατριών αποικιών στη Βόρεια Αμερική το 1783 μετά από την Αμερικανική Επανάσταση ήταν βαρύ πλήγμα για τη Βρετανία, καθώς της στέρησε τις πιο πολυπληθείς αποικίες της. Παρά το γεγονός αυτό, το βρετανικό ενδιαφέρον σύντομα στράφηκε προς την Αφρική, την Ασία και τον Ειρηνικό. Μετά την ήττα της Ναπολεόντειας Γαλλίας το 1815, η Βρετανία γνώρισε έναν αιώνα αδιαμφισβήτητης κυριαρχίας και επεξέτεινε την κυριαρχία της σε όλο τον κόσμο. Δόθηκε σταδιακή αυτονομία στις αποικίες με λευκό πληθυσμό, κάποιες από τις οποίες μετατράπηκαν σε κτήσεις.`;
    const actual1 = Tokenizer.charTranslateString(s);
    const expected = `kata tin epochi ton anakalipseon to 15o kai 16o aiona, i portogalia kai i ispania protostatisan stin eyropaiki exereinisi toy planiti kai egkathidrysan terasties polyplitheis aytokratories. epofthalmiontas ton ploito poy proseferan aytes oi aytokratories, i agglia, i gallia kai i ollandia archisan kai aytes na idrioyn apoikies kai emporika diktya stin ameriki kai tin asia.(4) mia seira polemon to 17o kai 18o aiona enantia stin ollandia kai ti gallia katestise tin agglia (vretania meta tin praxi enosis me ti skotia to 1707) kyriarchi apoikiaki dinami sti voreia ameriki kai tin india. i apoleia omos ton dekatrion apoikion sti voreia ameriki to 1783 meta apo tin amerikaniki epanastasi itan vari pligma gia ti vretania, kathos tis sterise tis pio polyplitheis apoikies tis. para to gegonos ayto, to vretaniko endiaferon sintoma strafike pros tin afriki, tin asia kai ton eiriniko. meta tin itta tis napoleonteias gallias to 1815, i vretania gnorise enan aiona adiamfisvititis kyriarchias kai epexeteine tin kyriarchia tis se olo ton kosmo. dothike stadiaki aytonomia stis apoikies me leyko plithysmo, kapoies apo tis opoies metatrapikan se ktiseis.`;
    expect(actual1).toBe(expected);
});


test("latinize RU", () => {
    const s = `Восприятие реальности в китайской философии основывалось на категории «рода» (кит., пиньинь lèi, палл. лэй). Эта категория позволяла моделировать поведение объектов, качеств и сил окружающей среды по отношению друг к другу. Природная и социальная реальность не отделялись друг от друга; точнее, существовало представление об изоморфизме в космосе и социуме, аналогии строения того и другого, и связанной с этим идее подражания космическим образцам. Гармоническое взаимодействие возможно между объектами одного и того же «рода», оно описывалось по аналогии между отношениями возгласа и эха, тела и тени, магнита и железа. Концепция лэй служила основной классификационных рядов в китайской культуре и занимала место причинности. В гармонически функционирующем мире каждая вещь (в том числе человек) занимает определённое положение, благодаря чему может вести себя сообразно своей природе. Если чьё-то поведение не соответствует его природе, это влияет на поведение всего «рода» и вызывает сбой в буквальном смысле в космическом масштабе. Однородные объекты (чаще всего основанием классификации служили инь-ян и у-син), какими бы далёкими друг от друга ни казались, представлялись взаимосвязанными и гармонически взаимодействующими, причём расцвет и преобладание одного рода (например, янского) был несовместим по времени с расцветом и преобладанием его противоположности. Подражание людей Небу влекло за собой представления об ответной реакции высших сил, причём действие и порождённый им ответ считались однородными; принцип ответа считался небесным законом. То, что правитель награждает и наказывает подданных, является справедливостью, а, следовательно, подражанием Небу. Китайское законодательство основывалось на принципе «плохо относиться к тому, кто плох», то есть преступление и наказание сходны, относятся к одному «роду»[10].`;
    const actual1 = Tokenizer.charTranslateString(s);
    const expected = `vosprijatie realnosti v kitajskoj filosofii osnovyvalos na kategorii 'roda' (kit., pinin lei, pall. lej). eta kategorija pozvoljala modelirovat povedenie obektov, kachestv i sil okruzajusej sredy po otnoseniju drug k drugu. prirodnaja i socialnaja realnost ne otdeljalis drug ot druga: tochnee, susestvovalo predstavlenie ob izomorfizme v kosmose i sociume, analogii stroenija togo i drugogo, i svjazannoj s etim idee podrazanija kosmicheskim obrazcam. garmonicheskoe vzaimodejstvie vozmozno mezdu obektami odnogo i togo ze 'roda', ono opisyvalos po analogii mezdu otnosenijami vozglasa i exa, tela i teni, magnita i zeleza. koncepcija lej sluzila osnovnoj klassifikacionnyx rjadov v kitajskoj kulture i zanimala mesto prichinnosti. v garmonicheski funkcionirujusem mire kazdaja ves (v tom chisle chelovek) zanimaet opredelennoe polozenie, blagodarja chemu mozet vesti sebja soobrazno svoej prirode. esli che-to povedenie ne sootvetstvuet ego prirode, eto vlijaet na povedenie vsego 'roda' i vyzyvaet sboj v bukvalnom smysle v kosmicheskom masstabe. odnorodnye obekty (chase vsego osnovaniem klassifikacii sluzili in-jan i u-sin), kakimi by dalekimi drug ot druga ni kazalis, predstavljalis vzaimosvjazannymi i garmonicheski vzaimodejstvujusimi, prichem rascvet i preobladanie odnogo roda (naprimer, janskogo) byl nesovmestim po vremeni s rascvetom i preobladaniem ego protivopoloznosti. podrazanie ljudej nebu vleklo za soboj predstavlenija ob otvetnoj reakcii vyssix sil, prichem dejstvie i porozdennyj im otvet schitalis odnorodnymi: princip otveta schitalsja nebesnym zakonom. to, chto pravitel nagrazdaet i nakazyvaet poddannyx, javljaetsja spravedlivostju, a, sledovatelno, podrazaniem nebu. kitajskoe zakonodatelstvo osnovyvalos na principe 'ploxo otnositsja k tomu, kto plox', to est prestuplenie i nakazanie sxodny, otnosjatsja k odnomu 'rodu'(10).`;
    expect(actual1).toBe(expected);
    expect(Tokenizer.tokenizeDocument(s)[8]).toBe("roda");
});
