#!/bin/sh
i=1
search="--$1"
found=""
for opt in $@; do
    if [ "$i" -gt 1 ]; then
        if [ "$found" = 1 ]; then
            if [ "$(echo "$opt" | grep '^--')" ]; then
                found=1
            else
                found="$opt"
            fi
            break
        elif [ "$opt" = "$search" ]; then
            found=1
        fi
    fi
    i=$((i + 1))
done
if [ "$found" ]; then
    echo "$found"
fi
