#!/usr/bin/bash
case $1 in
    f)
        tmux split-window "node dist/nr-fetcher-worker.js; zsh -i"
        node dist/nr-fetcher-zookeeper.js
        ;;
    na)
        npx nodemon dist/nr-main-net-agent.js
        ;;
    cold)
        node dist/nr-cold-start.js
        ;;
    sql)
        node dist/nr-inserter.js
        ;;
    schedule)
        node dist/nr-scheduler.js
        ;;
    compress)
        node dist/nr-compressor.js
        ;;
    process)
        tmux split-window "node dist/nr-resource-processor-worker.js; zsh -i"
        node dist/nr-resource-processor-zookeeper.js
        ;;
    bowh)
        node dist/nr-process-bows-per-host.js
        ;;
    bowr)
        node dist/nr-process-bows-per-relation.js
        ;;
    rank)
        node --max-old-space-size=8192 dist/nr-page-rank.js
        ;;
    *)
        cat $0
        ;;
esac
