#!/usr/bin/bash
case $1 in
    fetcher)
        tmux split-window "node dist/nr-fetcher-worker.js; zsh -i"
        node dist/nr-fetcher-zookeeper.js
        ;;
    net-agent-main)
        npx nodemon dist/nr-main-net-agent.js
        ;;
    cold)
        node dist/nr-cold-start.js
        ;;
    inserter)
        node dist/nr-inserter.js
        ;;
    scheduler)
        npx nodemon dist/nr-scheduler.js
        ;;
    compressor)
        node dist/nr-compressor.js
        ;;
    *)
        cat $0
        ;;
esac
