#!/usr/bin/bash
scriptsDir="$(dirname $0)"
projectDir="$("$scriptsDir/nr-project-wd")"
tmpFileTS="$projectDir/.gen-sql-code.ts"
(echo "export default {"
for statementFileName in $(ls "$projectDir/sql/"); do
    statementConstantName="$(printf "$statementFileName" | sed 's/\.[sS][qQ][lL]$//g')"
    statementFileLoc="$projectDir/sql/$statementFileName"
    echo   "	// $statementFileLoc"
    printf "	$statementConstantName: "'"'
    sqlformat --strip-comments "$statementFileLoc"\
        | awk '{printf "%s",gensub("[[:blank:]]+", " ", "1", $0" ")" "}'\
        | awk '{gsub(/[[:blank:]]+/," ");gsub(/[[:blank:]]+$/,"");print $0}'\
        | sed 's/"/'"'"'/g'\
        | sed 's/$/",/g'
done
echo "};") > "$tmpFileTS"
srcDir="$projectDir/src/main/ts"
if [ ! -d "$srcDir" ]; then mkdir -p "$srcDir"; fi
cp "$tmpFileTS" "$srcDir/sql.ts"
rm "$tmpFileTS"
